services:
  - type: web
    name: lead-scoring-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: AI_PROVIDER
        value: vertex_api_key
      - key: PROJECT_ID
        value: hackethon-413517
      - key: VERTEX_API_KEY
        value: <your-vertex-api-key>
      - key: MODEL
        value: publishers/google/models/gemini-2.0-flash